name: CI/CD Pipeline

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Type checking
      run: npm run type-check
      
    - name: Build project
      run: npm run build
      
    - name: Run tests
      run: npm run test:run
      
    - name: Run TypeScript example
      run: npm run dev
      
    - name: Run JavaScript example
      run: npm start
      
    - name: Run executable example
      run: ./example_usage.ts
      
    - name: Verify build artifacts
      run: |
        echo "Checking compiled files..."
        ls -la dist/
        ls -la dist/util/
        echo "Checking type definitions..."
        ls -la dist/*.d.ts
        ls -la dist/util/*.d.ts
        
    - name: Security audit
      run: npm audit --audit-level=moderate || echo "Security vulnerabilities found - please review"
      
    - name: Verify output
      run: |
        echo "✅ Build completed successfully"
        echo "✅ Tests passed"
        echo "✅ Examples executed successfully"
        echo "✅ All CI checks passed" 
